### ISSUE TITLE
Compiling *.protoc from external jar.

### ISSUE THREAD

**Issue by atais** [sbt/sbt-protobuf#54]
Hello.
I am quite confused how to setup this plugin.

I checked readme many times, also checked other issues and here is what I got so far:

in **plugins.sbt** apart from `addSbtPlugin` I had to also add `protoc-jar`. I followed instructions from https://github.com/sbt/sbt-protobuf/issues/44 , but it was really unclear why I need to do so, since in readme it never mentiones that. Anyway:
```
addSbtPlugin("com.github.gseitz" % "sbt-protobuf" % "0.6.3")
libraryDependencies += "com.github.os72" % "protoc-jar" % "3.0.0"
```

and my **build.sbt** (it is multi-module project)
```
lazy val `my-project` = (project in file("my-project"))
  .settings(
    protobufRunProtoc in ProtobufConfig := { args =>
      com.github.os72.protocjar.Protoc.runProtoc("-v300" +: args.toArray)
    },
    sourceDirectories in ProtobufConfig += (protobufExternalIncludePath in ProtobufConfig).value,
    version in ProtobufConfig := "3.0.0",
    libraryDependencies ++= Seq(
      "com.company" %% "protos" % "1" % ProtobufConfig.name
    )
  )
  .enablePlugins(ProtobufPlugin)
```
Now since I want to compile with version `3.0.0`, I added appropriate `version in ProtobufConfig`, but to my surprise, without 
```
sourceDirectories in ProtobufConfig += (protobufExternalIncludePath in ProtobufConfig).value,
```
it won't even pick up the sources from `target/protobuf_external` (but they were there).

Now after: `sbt "project my-project" compile`
I get:

```
[info] Compiling 14 protobuf files to.../target/scala-2.11/src_managed/main/compiled_protobuf
protoc-jar: protoc version: 300, detected platform: linux/amd64
[info] Compiling schema .../target/protobuf_external/google/protobuf/wrappers.proto
[info] Compiling schema .../target/protobuf_external/google/protobuf/duration.proto
[info] Compiling schema .../target/protobuf_external/google/protobuf/any.proto
...
[info] Compiling schema .../target/protobuf_external/main/protobuf/MYPROTOSCHEMA.proto
...
protoc-jar: executing: [/tmp/protoc554822369016551385.exe, -I/.../src/main/protobuf, -I/.../target/protobuf_external, --java_out=/.../target/scala-2.11/src_managed/main/compiled_protobuf, ....]
[info] Compiling protobuf
[info] Protoc target directory: .../target/scala-2.11/src_managed/main/compiled_protobuf
[info] Compiling 4 Scala sources and 68 Java sources to ...target/scala-2.11/classes ...
```

But I cannot find compiled classes in `src_managed/main/` and of course Java/Scala compilation fails.
What am I missing?

**Comment by atais** [comment]
The sources were compiled, but somehow the outcome is different, so I got some compilation error, but not because of missing sources. Sorry.
